version: '3.8'

services:
  postiz:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: postiz
    restart: always
    environment:
      # === Required Settings for local development
      MAIN_URL: "http://localhost:5000"
      FRONTEND_URL: "http://localhost:5000"
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:5000/api"
      JWT_SECRET: "random-string-for-local-development-only"
      DATABASE_URL: "postgresql://postiz-local:postiz-local-pwd@postiz-postgres:5432/postiz-db-local"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true"
      DISABLE_REGISTRATION: "false"
      NOT_SECURED: "true"  # For local development only

      # === Storage Settings
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"

      # === Misc Settings
      API_LIMIT: 30
      NX_ADD_PLUGINS: false

      # === X Platform Settings
      X_API_KEY: "z8yYnxXcfq9P6sibJbRbjCmsc"
      X_API_SECRET: "sGHWMyugXyYVa5VWPduvm22hfOZcq27qTyU9LvvKMp0p6yx247"
      X_URL: "http://localhost:4200"

    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    ports:
      - 5000:5000
      - 4200:4200
    networks:
      - postiz-network
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy

  postiz-postgres:
    # ref: https://hub.docker.com/_/postgres
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-local-pwd
      POSTGRES_USER: postiz-local
      POSTGRES_DB: postiz-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postiz-network
    healthcheck:
      test: pg_isready -U postiz-local -d postiz-db-local
      interval: 10s
      timeout: 3s
      retries: 3

  postiz-redis:
    # ref: https://hub.docker.com/_/redis
    image: redis:7-alpine
    container_name: postiz-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - postiz-network
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data

volumes:
  postgres-volume:
    external: false
  postiz-redis-data:
    external: false
  postiz-config:
    external: false
  postiz-uploads:
    external: false

networks:
  postiz-network:
    external: false